### ISSUE TITLE
Bug in blasfeo_dgemm_nn

### ISSUE THREAD

**Issue by FreyJo** [giaf/blasfeo#20] opened 2018-02-16 11:45 UTC
Hey guys,

I am using BLASFEO_VERSION = HIGH_PERFORMANCE and  BLASFEO_TARGET = X64_INTEL_SANDY_BRIDGE, which worked quite well for me before.
But now I got wrong results using blasfeo_dgemm_nn. I wrote the following minimal example:

#include <math.h>
#include <stdio.h>
#include <stdlib.h>

// blasfeo
#include <blasfeo/include/blasfeo_target.h>
#include <blasfeo/include/blasfeo_common.h>
#include <blasfeo/include/blasfeo_d_aux.h>
#include <blasfeo/include/blasfeo_d_aux_ext_dep.h>
#include <blasfeo/include/blasfeo_v_aux_ext_dep.h>
#include <blasfeo/include/blasfeo_d_blas.h>
int main() {
    int nx = 8;
    int nu = 2;
    int nZ = 4;
    struct blasfeo_dmat B;
    struct blasfeo_dmat A;
    struct blasfeo_dmat result;

    double *some_doubles;
    some_doubles = (double*) calloc(10, sizeof(double));
    for (int ii = 0; ii < 10; ii++) {
        some_doubles[ii] = (double) ii;
    }

    blasfeo_allocate_dmat(nx, nx+nu, &B); //    
    blasfeo_allocate_dmat(nZ, nx, &A); //    
    blasfeo_allocate_dmat(nZ, nu, &result); //   

    for (int ii = 0; ii < nx; ii++) {
        blasfeo_pack_dmat(1,10, &some_doubles[0], 1, &B, ii,0);
    }
    for (int ii = 0; ii < 4; ii++) {
        blasfeo_pack_dmat(1,1, &some_doubles[1],1, &A, 0+ii,1+2*ii);
    }
    blasfeo_pack_dmat(1,1, &some_doubles[1],1, &A, 0,1);

    printf("A = \n");
    blasfeo_print_dmat(nZ,  nx, &A,0,0);
    printf("B_multiplication = \n");
    blasfeo_print_dmat(nx, nu, &B,0,nx);
    
    blasfeo_dgemm_nn(nZ, nu , nx, 1.0, &A, 0, 0, &B, 0, nx, 0.0, &A, 0, 0, &result, 0, 0);

    printf("A * B_multiplication: result = \n");
    blasfeo_print_dmat(nZ,  nu, &result,0,0);

    return 0;
}

This gives me:
`
A =
  0.00000   1.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000
  0.00000   0.00000   0.00000   1.00000   0.00000   0.00000   0.00000   0.00000
  0.00000   0.00000   0.00000   0.00000   0.00000   1.00000   0.00000   0.00000
  0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   0.00000   1.00000

B_multiplication =
  8.00000   9.00000
  8.00000   9.00000
  8.00000   9.00000
  8.00000   9.00000
  8.00000   9.00000
  8.00000   9.00000`
  8.00000   9.00000
  8.00000   9.00000

A * B_multiplication: result =
  8.00000   9.00000
  8.00000   9.00000
  0.00000   0.00000
  0.00000   0.00000

I will switch to using the REFERENCE instead of HP for now. Which gives the correct result:

A * B_multiplication: result =
  8.00000   9.00000
  8.00000   9.00000
  8.00000   9.00000
  8.00000   9.00000

**Comment by tmmsartor** [comment] 2018-02-16 14:44
This is caused by some error in the 2x2 kernel, as quick fix you can 
comment out `MIN_KERNEL_SIZE = 2x2` in `Makefile.rule`.

**Comment by tmmsartor** [comment] 2018-02-18 18:07
[Here](https://github.com/tmmsartor/blasfeo/tree/hotfix_degemm_4x2_inner_store) a proper fix

**Comment by giaf** [comment] 2018-02-19 16:09
Merged now, thanks Jonathan for point it out and Tommaso for fixing!

**Closed by giaf** 2018-02-19 16:09 UTC
